name: ascii_qr
description: Create ASCII QR codes in Dart.  Like console_qr, but with no Flutter dependency.
version: 1.0.1
repository: https://github.com/ManyMath/ascii_qr

environment:
  sdk: ^3.5.3

dependencies:
  qr: ^3.0.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
